travis:
  secure:
    BINSTAR_TOKEN: mZol0zYryoSNjlWaqSR+lmuR4WG7AtQrCs+jSOzBXfX5lIQGxyZP5HPh4SKBpOy6sCTkay7U6cBjK3zS5eByQXzfPNujD3lZmkxcXYB7PuJgMLAQ5EhpYOsTFGdvAP2TpRBRDkAl8gjvzQlq6M6QuyX713QEeHSvdTap4MKtb/mK5NvnkXY75r8G97bnmzw8evqmjuEfGb+3UpD2kKQPE/I3M5syUOtQH2gN2ulPLJd1gbpzImpfgPsLjRMD+5jIWmx2LOsbrPJ5ZLtAapLjUlVBQoBQfAvyZNaxT1rJjTTDUyXju/Sx0v3zm2xGVbtVdwcwVyMpJpm5rhU46j+R5DPJZBNI9PMuWZR1B2+8qYdSrE9+P+a1dMt/2cFUGtTUCB2SgB7djbFAl3PZEa/c5WN+hm15TY31UaiIGWW/Jbp18PGRc+agzIphmqjnuMBQgI6LSd6qeH+DnQ2fZviwlaahwSw/SUrNRXk1097z1k9SfYQdE5Md9xXz+pEfk9SPChJdUlV/eh/vX2uElbm+SNjRztEz4X6o1FF5qH/YWha7wSpz/FqjDE8hlhPGqO/3nyWx6U15aboa56/QNE5Jh+AGerdzg8yfMJ9XsT8gs84L1R7FAzdY7O6vvh6EfdkcY5jmxNeJGarSTwGSGALGIz9xaf1ImcBj5m5sNVW5Iok=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
